spring:
  application:
    name: product
  rabbitmq:
    host: localhost
    port: 15672
    username: user
    password: password
    virtual-host: /
    connection-timeout: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
